version: "3"

services:
  websocket:
    build:
      context: ./Websocket
      dockerfile: Dockerfile
    ports:
      - "3001:3001"
      
  dashboard:
    build:
      context: ./Dashboard
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
